#!/bin/bash

# The version string should be supplied as a command line argument

cp ../presets/main/export_presets.cfg export_presets.cfg

sed -i "s/VERSION/$1/g" export_presets.cfg

godot="/home/andrew/apps/Godot_v4.2.2-stable_linux.x86_64"

$godot --headless --export-release "Linux/X11"

$godot --headless --export-release "macOS"

$godot --headless --export-release "Windows Desktop"

zip -j ../deploy/LogicSimX-$1.x86_64.zip ../build/linux/LogicSimX-$1.x86_64
