#!/bin/bash

# Edit these values:
item_name="hack-computer"
resource_files='"res://mods/HackComputer.tscn", "res://mods/HackComputer.gd", "res://mod.tres", "res://mod.gd", "res://tools/hack_assembler.gd", "res://tools/hack_assembler.tscn", "res://tools/hack_disassembler.gd", "res://tools/hack_disassembler.tscn"'

cp ../presets/mods/export_presets.cfg export_presets.cfg

sed -i "s/NAME/$item_name/g" export_presets.cfg
sed -i "s@FILES@$resource_files@g" export_presets.cfg

godot="/home/andrew/apps/Godot_v4.2.1-stable_linux.x86_64"

$godot --headless --export-release "Linux/X11"

$godot --headless --export-release "macOS"

$godot --headless --export-release "Windows Desktop"
